
---

apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: start

spec:
  params:
    - name: cicdContextName
      type: string

    - name: invokerUid
      type: string

    - name: gitAppName
      type: string

    - name: appTag
      type: string

    - name: commitId
      type: string
      default: none

    - name: relatedCicdContextDataId
      type: string
      default: none

    - name: relatedPipelineRunUid
      type: string
      default: none

    - name: relatedPipelineName
      type: string
      default: none

    - name: triggeredBySystem
      type: string

    - name: triggeredByDescription
      type: string

    - name: originalRequestBody
      type: string

    - name: uniqueString
      type: string

    - name: gitCloneUrl
      type: string

  workspaces:
    - name: cicdstatemgr-secrets
      description: cicdstatemgr secrets workspace
    - name: cicdstatemgr-configs
      description: cicdstatemgr configs workspace


  #---------------------
  # T A S K S
  #---------------------
  tasks:

      #---------------------
      # Start
      #---------------------
    - name: start
      taskRef:
        name: start

      workspaces:
        - name: cicdstatemgr-configs
          workspace: cicdstatemgr-configs
        - name: cicdstatemgr-secrets
          workspace: cicdstatemgr-secrets

      params:
        - name: cicdContextName
          value: $(params.cicdContextName)
        - name: pipelineRunUid
          value: $(context.pipelineRun.name)
        - name: invokerUid
          value: $(params.invokerUid)
        - name: gitAppName
          value: $(params.gitAppName)
        - name: appTag
          value: $(params.appTag)
        - name: commitId
          value: $(params.commitId)

        - name: relatedCicdContextDataId
          value: $(params.relatedCicdContextDataId)
        - name: relatedPipelineRunUid
          value: $(params.relatedPipelineRunUid)
        - name: relatedPipelineName
          value: $(params.relatedPipelineName)
        - name: triggeredBySystem
          value: $(params.triggeredBySystem)
        - name: triggeredByDescription
          value: $(params.triggeredByDescription)

        - name: originalRequestBody
          value: $(params.originalRequestBody)

        - name: uniqueString
          value: $(params.uniqueString)
        - name: gitCloneUrl
          value: $(params.gitCloneUrl)

      #---------------------------
      # Finish success
      #---------------------------
    - name:  finish-success
      taskRef:
        name: handle-event

      runAfter:
        - start

      workspaces:
        - name: cicdstatemgr-configs
          workspace: cicdstatemgr-configs
        - name: cicdstatemgr-secrets
          workspace: cicdstatemgr-secrets

      when:
        - input: "$(tasks.start.results.last-exit-code)"
          operator: in
          values: ["0"]

      #conditions:
      #  - conditionRef: exit-code-is-success
      #    params:
      #      - name: exit-code
      #        value: $(tasks.start.results.last-exit-code)

      params:
        - name: cicdContextDataId
          value: $(tasks.start.results.cicdContextDataId)
        - name: pipelineRunUid
          value: $(context.pipelineRun.name)
        - name: pipelineName
          value: start
        - name: eventName
          value: success
        - name: exitWithExitCode
          value: "0"

      #---------------------------
      # Finish failure
      #---------------------------
    - name: finish-failure

      taskRef:
        name: handle-event

      runAfter:
        - start

      workspaces:
        - name: cicdstatemgr-configs
          workspace: cicdstatemgr-configs
        - name: cicdstatemgr-secrets
          workspace: cicdstatemgr-secrets

      when:
        - input: "$(tasks.start.results.last-exit-code)"
          operator: notin
          values: ["0"]

      #conditions:
      #  - conditionRef: exit-code-is-failure
      #    params:
      #      - name: exit-code
      #        value: $(tasks.start.results.last-exit-code)

      params:
        - name: cicdContextDataId
          value: $(tasks.start.results.cicdContextDataId)
        - name: pipelineRunUid
          value: $(context.pipelineRun.name)
        - name: pipelineName
          value: start
        - name: eventName
          value: failure
        - name: exitWithExitCode
          value: "1"
