
---

apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: start
  annotations:
    # https://tektoncd.slack.com/archives/CKUSJ2A5D/p1606222895139800
    # https://github.com/tektoncd/triggers/pull/842
    triggers.tekton.dev/old-escape-quotes: "true"
spec:
  params:
    - name: cicdContextName

    - name: invokerUid

    - name: gitAppName

    - name: appTag

    - name: commitId

    - name: triggeredBySystem

    - name: triggeredByDescription

    - name: relatedCicdContextDataId
      default: "none"

    - name: relatedPipelineRunUid
      default: "none"

    - name: relatedPipelineName
      default: "none"

    - name: originalRequestBody

    - name: uniqueString

    - name: gitCloneUrl

  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: start-$(tt.params.cicdContextName)-$(tt.params.gitAppName)-
      spec:
        serviceAccountName: cicd-tekton

        pipelineRef:
          name: start

        params:
          - name: cicdContextName
            value: $(tt.params.cicdContextName)

          - name: relatedCicdContextDataId
            value: $(tt.params.relatedCicdContextDataId)

          - name: relatedPipelineRunUid
            value: $(tt.params.relatedPipelineRunUid)

          - name: relatedPipelineName
            value: $(tt.params.relatedPipelineName)

          - name: invokerUid # the invoking user uid
            value: $(tt.params.invokerUid)

          - name: gitAppName
            value: $(tt.params.gitAppName)

          - name: appTag
            value: $(tt.params.appTag)

          - name: commitId
            value: $(tt.params.commitId)

          - name: triggeredBySystem
            value: $(tt.params.triggeredBySystem)

          - name: triggeredByDescription
            value: $(tt.params.triggeredByDescription)

          - name: originalRequestBody
            value: $(tt.params.originalRequestBody)

          - name: uniqueString
            value: $(tt.params.uniqueString)

          - name: gitCloneUrl
            value: $(tt.params.gitCloneUrl)

        workspaces:

          - name: cicdstatemgr-secrets
            secret:
              secretName: cicdstatemgr-secrets
              items:
                - key: cicdstatemgr-secrets.yaml
                  path: cicdstatemgr-secrets.yaml

          - name: cicdstatemgr-configs
            configmap:
              name: cicdstatemgr-configs

---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: start-via-git
spec:
  params:
    - name: cicdContextName
      value: dev

    - name: invokerUid # the invoking user uid!
      value: $(extensions.invokedByPrincipalId)

    - name: gitAppName
      value: $(extensions.gitAppName)

    - name: appTag
      value: $(extensions.appTag)

    - name: commitId
      value: $(extensions.commitId)

    - name: triggeredBySystem
      value: "github"

    - name: triggeredByDescription
      value: "Github push of git tag $(extensions.gitAppName):$(extensions.appTag)"

    - name: originalRequestBody
      value: $(body)

    - name: uniqueString
      value: $(extensions.commitId)

    - name: gitCloneUrl
      value: $(body.repository.clone_url)



---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: start-via-change-context
spec:
  params:

    - name: cicdContextName
      value: $(extensions.targetCicdContextName)

    - name: invokerUid
      value: "<@$(extensions.slackUserId)>"

    - name: gitAppName
      value: $(extensions.gitAppName)

    - name: appTag
      value: $(extensions.appTag)

    - name: commitId
      value: $(extensions.commitId)

    - name: gitCloneUrl
      value: $(extensions.gitCloneUrl)

    - name: triggeredBySystem
      value: "slack"

    - name: triggeredByDescription
      value: "Slack button press by <@$(extensions.slackUserId)>"

    - name: relatedCicdContextDataId
      value: $(extensions.relatedCicdContextDataId)

    - name: relatedPipelineRunUid
      value: $(extensions.relatedPipelineRunUid)

    - name: relatedPipelineName
      value: $(extensions.relatedPipelineName)

    - name: originalRequestBody
      value: $(body)

    - name: uniqueString
      value: $(extensions.commitId)


---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: start-via-cmd-startdeploy
spec:
  params:

    - name: cicdContextName
      value: $(extensions.targetCicdContextName)

    - name: invokerUid
      value: "<@$(extensions.slackUserId)>"

    - name: gitAppName
      value: $(extensions.gitAppName)

    - name: appTag
      value: $(extensions.appTag)

    - name: gitCloneUrl
      value: $(extensions.gitCloneUrl)

    - name: triggeredBySystem
      value: "slack slash cmd"

    - name: triggeredByDescription
      value: "Slack slash command /start-app-deploy by <@$(extensions.slackUserId)>"

    - name: originalRequestBody
      value: $(body)

    - name: uniqueString
      value: $(extensions.uniqueString)
